POST http://localhost:3000/auth/sign-in
Content-Type: application/json

{
    "name":"drugi",
    "email":"marko@gmail.com",
    "password":"lozinka"
}
###
GET http://localhost:3000/user

###
POST http://localhost:3000/post
Content-Type: application/json

{
    "content":"ovo je moj p post",
    "photo":"",
    "userID":"1"
}
###
GET http://localhost:3000/post

###
GET http://localhost:3000/post/1

###
DELETE  http://localhost:3000/post/2
Content-Type: application/json

{ 
    "userId":"1"
}
//COMMENTS
###
POST http://localhost:3000/comment
Content-Type: application/json

{ 
    "content":"user 1 komenratise post 1",
     "userId":"1",
     "postId":"1"

}
###
get http://localhost:3000/post/1/comments

###
DELETE  http://localhost:3000/comment
Content-Type: application/json

{ 
    "commentId":"4",
      "userId":"1",
     "postId":"1"
}

###
POST http://localhost:3000/comment/like
Content-Type: application/json

{ 
    "commentId":"1",
    "userId":"1"
}
###
GET http://localhost:3000/comment/1/like

//LIKES
###
post  http://localhost:3000/post/like
Content-Type: application/json

{ 
   
      "userId":"4",
     "postId":"5"
}
###
GET   http://localhost:3000/post/5/like
