POST http://localhost:3000/auth/sign-in
Content-Type: application/json

{
    "name":"marko",
    "email":"darko@gmail.com",
    "password":"lozinka"
}

###
POST http://localhost:3000/auth/log-in
Content-Type: application/json

{
    "email":"darko@gmail.com",
    "password":"lozinka"
}

###
GET http://localhost:3000/user

###
POST http://localhost:3000/post
Content-Type: application/json

{
    "content":"ovo je moj p post napravljenj od strane veljka me dksafjlkdsafjjdslafjkldsajfklds;jafkjsadkfjsadkl;fjdsaf;aj;fjdsa;flidjsakl;fjsadlfk",
    "photo":"",
    "userID":"3"
}
###
GET http://localhost:3000/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo0LCJ1c2VybmFtZSI6Im1hcmtvIiwicGFzc3dvcmRfaGFzaCI6IiQyYiQxMCRxRmVLcE1PelB0RmpEN2p1REZ3TTkuZzNKbGZtblc4Q3RPSEN0b0tUek1ESjlCZzJNWlFzLiIsImdvb2dsZV9pZCI6bnVsbCwicHJvZmlsZV9pbWFnZSI6bnVsbCwiYmlvZ3JhcGh5IjpudWxsLCJlbWFpbCI6ImRhcmtvQGdtYWlsLmNvbSJ9LCJpYXQiOjE3NDAxNDcyNzksImV4cCI6MTc0MDIzMzY3OX0.KnR1WDGWAt3aHDJD-174u7GTfHK1walNbe8Ccd66ShY
###
GET http://localhost:3000/post/1

###
DELETE  http://localhost:3000/post/2
Content-Type: application/json

{ 
    "userId":"1"
}
//COMMENTS
###
POST http://localhost:3000/comment
Content-Type: application/json

{ 
    "content":"user 1 komenratise post 1",
     "userId":"1",
     "postId":"1"

}
###
get http://localhost:3000/post/1/comments

###
DELETE  http://localhost:3000/comment
Content-Type: application/json

{ 
    "commentId":"4",
      "userId":"1",
     "postId":"1"
}

###
POST http://localhost:3000/comment/like
Content-Type: application/json

{ 
    "commentId":"1",
    "userId":"1"
}
###
GET http://localhost:3000/comment/1/like

//LIKES
###
post  http://localhost:3000/post/like
Content-Type: application/json

{ 
   
      "userId":"4",
     "postId":"5"
}
###
GET   http://localhost:3000/post/5/like
